services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: local_db
    ports:
      - "5432:5432"
    volumes:
      - ./Contexts/Ecommerce/Common/Infrastructure/Persistence/DbSchema.sql:/docker-entrypoint-initdb.d/0000.sql
      - ./Contexts/Ecommerce/Store/Infrastructure/Persistence/DbSchema.sql:/docker-entrypoint-initdb.d/0001.sql
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - ./Tools/Pgadmin/Servers.json:/pgadmin4/servers.json