services:
  db:
    container_name: pg_container
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: local_db
    ports:
      - "5432:5432"
    volumes:
      - ./api/Contexts/Ecommerce/Store/Infrastructure/Persistence/Schema.sql:/docker-entrypoint-initdb.d/ecommerce_store_schema.sql
  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
